hooks/CartPageHooks/cart-page-hook.ts
hooks/GeneralHooks/QuickOrderHooks/quick-order-hook.ts
hooks/LanguageHook/Multilanguages-hook.ts
hooks/ProductDetailHook/product-detail-hook.ts
hooks/order-listing-page-hook/cart-order-history-hook.ts
hooks/order-listing-page-hook/order-list-hook.ts
hooks/product-listing-hooks/product-listing-hook.tsx
interfaces/checkout-page-interface.tsx
interfaces/filters-view-interface.ts
interfaces/product-card-interface.ts
interfaces/products-view-interface.ts
services/api/auth/get_userrole_api.ts
services/api/auth/guest-login-api.ts
services/api/auth/login_api.ts
services/api/auth/token-login-api.ts
services/api/cart-page-api/add-to-cart-api.ts
services/api/cart-page-api/cart-listing-api.ts
services/api/my-order-api/order-history-api.ts
store/slices/auth/login_slice.ts
store/slices/auth/token-login-slice.ts
store/slices/general_slices/selected-multilanguage-slice.ts
store/slices/order-listing-page-slice/order-listing-page-slice.ts

It includes changes done in hook and api files of quick order page and cart page.

changes done for quick order page, update cart and multi-lingual

---

hooks/CatalogHooks/catalogHook.ts
hooks/product-listing-hooks/product-listing-hook.tsx
interfaces/filters-view-interface.ts
interfaces/product-card-interface.ts
interfaces/products-view-interface.ts
pages/product-category/index.tsx
services/api/product-catalog-api/delete-item-from-catalog-api.tsx
services/api/product-catalog-api/put-product-to-catalog-api.tsx
services/api/product-listing-page-api/missing-parts-api.ts

changes done for catalog

---

hooks/GeneralHooks/QuickOrderHooks/quick-order-hook.ts
store/slices/general_slices/quick-order-slice.ts

Quick order - deleting a particular product wasn't updating the array and deleted item was not getting removed.

quick order api changes

---

hooks/CheckoutHooks/checkout-page-hook.ts
interfaces/checkout-page-interface.tsx
services/api/auth/registration_api.ts
services/api/auth/reset-password-link-api.ts
validation/registrationValidation.ts

1. currency changes in checkout hook
2. registration password validation changes

issues solved

---

hooks/GeneralHooks/NavbarHooks/NavbarHook.ts
hooks/LanguageHook/Multilanguages-hook.ts
pages/brand-product/[category-slug]/[product_id]/index.tsx
pages/brand/[category]/index.tsx
pages/cart.tsx
pages/catalog-product/[category-slug]/[product_id]/index.tsx
pages/catalog/[category]/index.tsx
pages/catalog/index.tsx
pages/checkout.tsx
pages/login.tsx
pages/myOrder/index.tsx
pages/product-category/[category]/index.tsx
pages/product-category/index.tsx
pages/product/[category-slug]/[product_id]/index.tsx
pages/profile.tsx
pages/register.tsx
pages/search/index.tsx
pages/thankyou/[id]/index.tsx
pages/thankyou/index.tsx
pages/wishlist.tsx
services/api/general_apis/default-currency-api.ts
services/api/general_apis/meta-tag-api.ts
services/api/general_apis/multilanguage-api.ts
store/slices/general_slices/multi-currency-slice.ts
store/slices/general_slices/multilang-slice.ts
store/slices/general_slices/selected-multilanguage-slice.ts

Home Page has different sections. Each section was fetching data from different api which leads to multiple api calls on client side.
This has been tested manually. No automation test cases has been written.

home page api calls reduced

---

hooks/GeneralHooks/NavbarHooks/LinguisticsAndForexHook.ts
hooks/HomePageHooks/DisplayTagHooks.ts
store/slices/general_slices/multi-currency-slice.ts

Multi-currency not working on home page fixed, but is it a permanent fix? Not sure... 
It includes changes made in useEffect and global redux store

fixed - multi-currency not working on home page  

---

hooks/GeneralHooks/NavbarHooks/NavbarHook.ts

fixed - currency value was not getting updated in the navbar after changing from the dropdown box.

currency value was not getting updated in the navbar after changing from the dropdown box.

---

README.md
hooks/GeneralHooks/QuickOrderHooks/quick-order-hook.ts
hooks/GeneralHooks/SearchHooks/search-hook.tsx
services/api/general_apis/multilanguage-api.ts

issues fixed - 
1. Items were added by enter key and by button click also
2. If the search input field is blank then it can't redirect to the listing page
3. multi lang API issue solved

Issues fixed and functionality changes

---

hooks/CartPageHooks/cart-page-hook.ts
services/api/auth/guest-login-api.ts
services/api/auth/token-login-api.ts
services/api/cart-page-api/add-to-cart-api.ts
services/api/cart-page-api/cart-listing-api.ts
store/slices/auth/token-login-slice.ts
store/slices/general_slices/profile-page-slice.ts

#checklist
1. Guest quotations can be merged after login as guest
2. visitor address form button validation msg if the user doesn't select the checkbox of login as guest

Guest Flow changes

---

hooks/CartPageHooks/cart-page-hook.ts

1 - Mobile Otp Verificcation api file added
2 - email otp verification api file added
3 - few unwanted file deleted.
4 -  config file changes.

feat:mobile email auth api file added:sk

---

hooks/CartPageHooks/cart-page-hook.ts

1 - Cart total not getting update issue is fixed.

fix:cart total is not getting updated issue fixed:sk

---

pages/product-category/[category]/index.tsx
pages/product-category/index.tsx

- Imports for components changed

Product Listing Page changes

---

hooks/HomePageHooks/DisplayTagHooks.ts
services/api/home_page_api/home-display-tag-api.ts

#Description
- Error handling by common hook file.

Display tag Error message 

---

hooks/product-listing-hooks/product-listing-filter-hook.ts

Filters issue

---

hooks/product-listing-hooks/product-listing-hook.tsx
services/api/product-listing-page-api/get-product-list-api.ts

- Handle Pagination Function modified

Handle Pagination Function modified

---

hooks/product-listing-hooks/product-listing-hook.tsx
services/api/product-listing-page-api/get-filters-api.ts

- use common callGetAPI function for filter get api

Use Common function for api calling

---

package-lock.json
package.json
postcss.config.js

`postcss-flexbugs-fixes',
[
'postcss-preset-env',
{
autoprefixer: {
flexbox: 'no-2009',
},
stage: 3,
features: {
customProperties: false,
},
},
],`

perf: css minification config in postcss file

---

hooks/CartPageHook/useAddToCart.ts
hooks/CartPageHook/useCartPageHook.ts
store/slices/cart-slices/cart-local-slice.ts

cart page fixed

---

hooks/ProductDetailPageHooks/useProductDetail.ts

- Add to cart drawer and product detail page skeleton
- variant loader

fix: product detail hook modified

---

hooks/GeneralHooks/NavbarHooks/NavbarHook.ts
services/api/auth/logout-api.ts
store/root-reducer.ts
store/slices/auth/logout-slice.ts
store/slices/auth/token-login-slice.ts

- rootReducer
- logout slice
`const rootReducer = (state: any, action: any) => {
if (action.type === resetStore.type) {
state = {}; // Clear the entire state
}
return appReducer(state, action);
};`

feat: logging out user and post logout clearing the persisting state

---

hooks/CartPageHook/useAddToCart.ts
hooks/CartPageHook/useFetchCartItems.ts
hooks/GeneralHooks/breadcrumbs-hook.ts
hooks/HomePageHooks/BannerHook.ts
hooks/HomePageHooks/DisplayTagHooks.ts
hooks/OrderDetailHook/useOrderDetailHook.tsx
hooks/ProductDetailPageHooks/useProductDetail.ts
hooks/ProductListPageHooks/useProductListFilterHook.ts
hooks/ProductListPageHooks/useProductsDataHook.ts
hooks/WishlistHooks/useWishlistHook.ts
services/api/cart-apis/cart-listing-api.ts
services/api/general-apis/breadcrumbs-api.ts
services/api/home-page-apis/banner-api.ts
services/api/home-page-apis/home-display-tag-api.ts
services/api/order-detail-apis/order-detail-api.ts
services/api/product-detail-page-apis/get-product-detail.ts
services/api/product-detail-page-apis/get-product-variants.ts
services/api/product-listing-page-apis/get-filters-api.ts
services/api/product-listing-page-apis/get-product-list-api.ts
services/api/wishlist-apis/wishlist-api.ts
utils/api_sdk_registry.ts

handling multiple API versions

API Version changes

---

.gitignore
hooks/BulkOrder/bulk-order-hook.ts
hooks/BulkOrder/bunch-order-hook.ts
hooks/BulkOrder/custom-market-order-hook.ts
hooks/BulkOrder/market-order-hook.ts
hooks/QuickOrder/quick-order-hook.ts
services/api/quick-order-apis/get-customer-item-name.ts
services/api/quick-order-apis/post-quick-order.ts
utils/api_sdk_registry.ts

- quick order hook and API files added
- bulk order api files added

Quick and bulk order

---

hooks/ProductListPageHooks/useProductsDataHook.ts
services/api/product-listing-page-apis/get-product-list-api.ts

Load more btn used to load only next 4 items at a time. Made it to load 12 items. 
Rearranged and refactor useProductList hook code and fixed bugs of search functionality.

fix: load-more btn and hook files changes

---

utils/api_sdk_registry.ts

Version, method and entity added for respective get APIs in api_sdk_registry file

fix: version method entity added

---

hooks/AuthHooks/useLoginHook.ts
hooks/CartPageHook/useAddToCart.ts
hooks/GeneralHooks/useNavbar.ts
hooks/WishlistHooks/useWishlistHook.ts
routes/ProtectedRoute.tsx
services/api/auth/get-token-from-login-api.ts
services/api/general-apis/default-currency-api.ts
services/api/general-apis/multilanguage-api.ts
store/root-reducer.ts
store/slices/general_slices/multi-currency-slice.ts
store/slices/general_slices/multilang-slice.ts

Have passed 'appConfig' parameter to api files and slices where it was missing. Also Logout func developed

fix: app config changes

---

hooks/LanguageHook/Multilanguages-hook.ts
store/slices/general_slices/multilang-slice.ts
utils/api_sdk_registry.ts

- language hook and slice modified

Navbar fixes (language)

---

hooks/CartPageHook/useAddToCart.ts
services/api/cart-apis/get-quotation-api.ts
store/slices/cart-slices/cart-local-slice.ts

Cart page UI and API integration

Cart Page 

---

hooks/ProductDetailPageHooks/useProductDetail.ts
hooks/WishlistHooks/useAddToWishlistHook.ts

 Product detail and wishlist

---

hooks/ProductListPageHooks/useProductListFilterHook.ts

Filter Hook changed

---

hooks/CatalogHooks/useCatalog.ts
hooks/CheckoutPageHook/useGetOrderSummary.ts

- Store Credit functionality added
- Coupon code functionality added
- In create catalog function, validation added

Order Checkout Changes

---

hooks/OrderDetailHook/useOrderDetailHook.tsx
hooks/OrderListHooks/useOrderListHook.ts
services/api/order-detail-apis/order-detail-api.ts

 order list and details added

---

hooks/OrderListHooks/useOrderListHook.ts

Update order status in url

---

hooks/QuickOrder/useQuickOrderHook.ts
store/slices/quick-order-slice/quick-order-slice.ts

Quick order modifications

---

hooks/CartPageHook/useAddToCart.ts
hooks/CheckoutPageHook/useCheckout.ts
hooks/ProductDetailPageHooks/useCustomerReview.ts
hooks/ProductDetailPageHooks/useProductDetail.ts
hooks/QuickOrder/useQuickOrderHook.ts
store/slices/cart-slices/cart-local-slice.ts
store/slices/quick-order-slice/quick-order-slice.ts

- Loader added to the button 
- Local cart slice modified

Button Loader added

---

hooks/AuthHooks/useLoginHook.ts

- Loader added to login button

Login button loader

---

hooks/GoogleAnalytics/useGoogleAnalyticsHandler.ts
hooks/GoogleAnalytics/useGoogleAnalyticsOperationsHandler.ts
hooks/GoogleAnalytics/useInitializeGoogleAnalytics.ts
package-lock.json
package.json
pages/_document.tsx
pages/product-category/[category]/index.tsx
pages/product-category/index.tsx
pages/product/[category-slug]/[productId]/index.tsx
services/config/app-config.ts

Google analytics setup

---

hooks/CartPageHook/useAddToCart.ts
hooks/WishlistHooks/useAddToWishlistHook.ts

Improve UX by Replacing Toast Notification with "Added to Cart" Button on Add Cart Trigger 
https://github.com/user-attachments/assets/8ddcfabc-1353-496a-8804-13b8ad293bda
Remove Toast Notification for Items adding to Wishlist
https://github.com/user-attachments/assets/aa6f43a7-e971-4dae-a980-506efcbcf7df

Toast notifications removed

---

.github/ISSUE_TEMPLATE/feature_request.yaml

Added a template for contributors and people visiting summit, to request a feature that is missing in Summit or rather they would like to have it in.
Fixes # (issue)
Created feature_request.yaml file inside ISSUE_TEMPLATE folder

docs: :memo: feat_req template added

---

hooks/WishlistHooks/useAddToWishlistHook.ts

- Incorrect error msg was showing when failed to add item to wishlist or failed to remove item from wishlist

Incorrect err msg wishlist

---

hooks/CartPageHook/useAddToCart.ts
hooks/CheckoutPageHook/useCheckout.ts
hooks/CheckoutPageHook/useGetUserAddresses.ts
hooks/ProductDetailPageHooks/useProductDetail.ts
hooks/WishlistHooks/useAddToWishlistHook.ts
services/api/checkout/post-user-address-api.ts
utils/api_sdk_registry.ts

This PR contains changes in checkout process for guests and bug fixes for Product page.

Release 1 - Guest flow implementation and bug fixes

---

pages/brand-product/[category-slug]/[productId]/index.tsx

When clicking on a particular brand from the "Top Brands" section on the homepage, the product list for that brand does not load or function as expected. Even the product page does not open.
Fixes # (issue)

Release v1.1.1

---

interfaces/featured-collection-interface.ts
interfaces/tag-data-interface.ts

Interface added for Display tag data

Featured collection with variants card

---

hooks/AuthHooks/useRegisterUser.ts
pages/cart.tsx
pages/register.tsx

1. **New Master Component**  
- Added a new master component for the Cart Page to streamline UI and functionality integration.  
Let me know if additional changes are needed!

Cart Page Updates

---

hooks/ProductListPageHooks/useProductListPageHandlers.ts
interfaces/components-types.ts
pages/product-category/[category]/index.tsx
pages/product/[category-slug]/[productId]/index.tsx
services/api/home-page-apis/get-components-list.ts
services/api/seo-apis/sitemap-api.ts
utils/api_sdk_registry.ts
utils/handle-components-list.ts

Generating home page and product list page dynamically with the help of components received in an API at build time.

Dynamically generating pages with components at build time

---

hooks/ProductListPageHooks/useProductListFilterHook.ts

1. **Clear Filter Function**  
- Implemented a `clearFilter` function to allow users to reset all applied filters effortlessly.  
Let me know if any further adjustments are needed!

Clear Filter Function

---

hooks/AuthHooks/useRegisterUser.ts

Missing type added

---

hooks/ProductDetailPageHooks/useProductDetail.ts
pages/product-category/[category]/index.tsx
services/api/general-apis/get-pin-code-list-api.ts
utils/http-methods.ts

Pincode API integrated and it's validation handled on product page

feat: Pincode validation handled on Product Page 

---

hooks/HomePageHooks/useHomeBlogData.ts
hooks/HomePageHooks/usePromotionalBanner.ts
services/api/home-page-apis/blog-api.ts
services/api/home-page-apis/cta-banner-api.ts
services/api/home-page-apis/promotional-banner-api.ts
utils/api_sdk_registry.ts
utils/handle-components-list.ts

1. **Hook Files Added**  
- Created hooks for Blog and Promotional Category sections for better state management and data fetching.  
2. **API Files Added**  
- Added API files for Blog and Promotional Category data handling.  
- Registered the new APIs in `api_registry_sdk`.  
3. **Validation Enhancement**  
- Added `?` validation in `flattenComponentsList` to handle potential undefined values gracefully.  
Let me know if any further refinements are required!

Jewellery featured collection

---

interfaces/components-interface.ts
pages/product-category/[category]/index.tsx
services/api/home-page-apis/get-components-list.ts
utils/handle-components-list.ts

This PR modifies the codebase to accommodate changes in the API used to fetch the components list at build time. Updates were made to ensure compatibility with the new API structure.

feat: :alembic: structural changes of components api during build time

---

fetch-summit-settings.sh

Error handling if API fails to respond

fix 🐛 API Error Handling in bash file 

---

hooks/HomePageHooks/useHomeBlogData.ts
services/api/home-page-apis/blog-api.ts
utils/api_sdk_registry.ts
utils/dataFormat.ts

Hook and API files added for Home page blog section.
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Hook and API files for Home page blog section.

---

hooks/HomePageHooks/usePromotionalBanner.ts
services/api/home-page-apis/promotional-banner-api.ts

1. **API Integration**  
- Added a standard API call function in the API file to fetch promotional banner data.  
2. **Hook File**  
- Implemented a function in the hook file to fetch data from the API for seamless integration with the promotional banner component.  
Let me know if further adjustments are required!

Promotional Banner functions added
